export const allOrder = [
  {
    id: 0,
    nameReceiver: "Võ Duy Tạo",
    phoneReceiver: "0352811528",
    addressReceiver: "76/3 đường số 7 phường linh trung",
    message: "string",
    orderPrice: 0,
    deliveryPrice: 0,
    discount: 0,
    finalPrice: 0,
    orderStatus: 1,
    orderStatusString: "Ordered",
    buyDate: "2024-03-08T03:50:09.567Z",
    paymentStatus: 0,
    paymentStatusString: "Chưa thanh toán",
    paymentMethod: "string",
    userId: 0,
    orderDetails: [
      {
        id: 0,
        slug: "string",
        productId: 0,
        orderProductId: 0,
        feedbackId: 0,
        name: "string",
        image: "string",
        quantity: 0,
        typeId: 0,
        ram: "string",
        storageCapacity: "string",
        color: "string",
        price: 0,
        salePrice: 0,
      },
    ],
  },
  {
    id: 1,
    nameReceiver: "Võ Duy Tạo",
    phoneReceiver: "0352811528",
    addressReceiver: "76/3 đường số 7 phường linh trung",
    message: "string",
    orderPrice: 0,
    deliveryPrice: 0,
    discount: 0,
    finalPrice: 0,
    orderStatus: 3,
    orderStatusString: "Delivering",
    buyDate: "2024-03-08T03:50:09.567Z",
    paymentStatus: 0,
    paymentStatusString: "Đã thanh toán",
    paymentMethod: "string",
    userId: 0,
    orderDetails: [
      {
        id: 0,
        slug: "string",
        productId: 0,
        orderProductId: 0,
        feedbackId: 0,
        name: "string",
        image: "string",
        quantity: 0,
        typeId: 0,
        ram: "string",
        storageCapacity: "string",
        color: "string",
        price: 0,
        salePrice: 0,
      },
    ],
  },
  {
    id: 2,
    nameReceiver: "Võ Duy Tạo",
    phoneReceiver: "0352811528",
    addressReceiver: "76/3 đường số 7 phường linh trung",
    message: "string",
    orderPrice: 0,
    deliveryPrice: 0,
    discount: 0,
    finalPrice: 0,
    orderStatus: 5,
    orderStatusString: "Cancelled",
    buyDate: "2024-03-08T03:50:09.567Z",
    paymentStatus: 0,
    paymentStatusString: "Đã thanh toán",
    paymentMethod: "string",
    userId: 0,
    orderDetails: [
      {
        id: 0,
        slug: "string",
        productId: 0,
        orderProductId: 0,
        feedbackId: 0,
        name: "string",
        image: "string",
        quantity: 0,
        typeId: 0,
        ram: "string",
        storageCapacity: "string",
        color: "string",
        price: 0,
        salePrice: 0,
      },
    ],
  },
  {
    id: 2,
    nameReceiver: "Võ Duy Tạo",
    phoneReceiver: "0352811528",
    addressReceiver: "76/3 đường số 7 phường linh trung",
    message: "string",
    orderPrice: 0,
    deliveryPrice: 0,
    discount: 0,
    finalPrice: 0,
    orderStatus: 2,
    orderStatusString: "Confirmed",
    buyDate: "2024-03-08T03:50:09.567Z",
    paymentStatus: 0,
    paymentStatusString: "Đã thanh toán",
    paymentMethod: "string",
    userId: 0,
    orderDetails: [
      {
        id: 0,
        slug: "string",
        productId: 0,
        orderProductId: 0,
        feedbackId: 0,
        name: "string",
        image: "string",
        quantity: 0,
        typeId: 0,
        ram: "string",
        storageCapacity: "string",
        color: "string",
        price: 0,
        salePrice: 0,
      },
    ],
  },
  {
    id: 2,
    nameReceiver: "Võ Duy Tạo",
    phoneReceiver: "0352811528",
    addressReceiver: "76/3 đường số 7 phường linh trung",
    message: "string",
    orderPrice: 0,
    deliveryPrice: 0,
    discount: 0,
    finalPrice: 0,
    orderStatus: 4,
    orderStatusString: "Delivered",
    buyDate: "2024-03-08T03:50:09.567Z",
    paymentStatus: 0,
    paymentStatusString: "Đã thanh toán",
    paymentMethod: "string",
    userId: 0,
    orderDetails: [
      {
        id: 0,
        slug: "string",
        productId: 0,
        orderProductId: 0,
        feedbackId: 0,
        name: "string",
        image: "string",
        quantity: 0,
        typeId: 0,
        ram: "string",
        storageCapacity: "string",
        color: "string",
        price: 0,
        salePrice: 0,
      },
    ],
  },
];



